
//----------------------
// <auto-generated>
//     Generated REST API Client Code Generator v1.19.0.0 on 26.1.2025. 12:19:42
//     Using the tool Swagger Codegen CLI v3.0.34
// </auto-generated>
//----------------------



